### ISSUE TITLE
Model Checkpoint

### ISSUE THREAD

**Issue by MuhammadWaqar621** [abdur75648/End-To-End-Urdu-OCR-WebApp#1]
I'm not able to find a model checkpoint

**Comment by abdur75648** [comment]
@MuhammadWaqar621 The weights are uploaded, I just checked.
Since they're large files, they are uploaded as **Git LFS** (Large File Storage) files. 

This means that if you have not installed Git LFS on your system, these files in the repository will not be properly downloaded. So, make sure you have Git LFS & Initialized (can be checked with `git lfs version` command)

**Comment by humada05** [comment]
Hi @abdur75648 Im still not able to download the weights even with gif-lfs installed: https://github.com/abdur75648/End-To-End-Urdu-OCR-WebApp/issues/2

**Comment by abdur75648** [comment]
I have removed the model weights from Git LFS as the repository exceeded its data quota for LFS bandwidth. You can still access the weights and test samples by downloading them from the [Hugging Face repository](https://huggingface.co/spaces/abdur75648/UrduOCR-UTRNet) using the provided `download_files.sh` script.

Alternatively, you can clone the Hugging Face repository directly by following these steps:

1. Ensure you have [Git LFS installed](https://git-lfs.com):
   ```bash
   git lfs install
   ```

2. Clone the repository:
   ```bash
   git clone https://huggingface.co/spaces/abdur75648/UrduOCR-UTRNet
   ```

Let me know if you encounter any issues!

**Comment by VASEEM0044** [comment]
hi there .
the new yolo version is available can i switch to latest version YOLO11.
